.TH WIFI-QR 1 "MAY 31 2020"
.SH NAME
wifi-qr \-  WiFi Share and Connect with QR
.SH SYNOPSIS
.B wifi-qr
.R [  -g  |  -c  |  -t  |  -s  |  -f  <file> |  -p  |  -q  |  -v  |  -h  ]
.br
.SH DESCRIPTION
 WiFi password share via QR codes
 Shares WiFi SSID and password via a QR code.
 Generate a QR code of a WiFi network with its password.
 Scan QR codes and easily connect to WiFi Networks.

 For Android, OS version 10 and above is supported.
 For iOS, the Shortcuts app supports generating WiFi QR codes.
.sp

.PP
.SH OPTIONS
wifi-qr option  
.TP
.B -g 	GUI Main Menu 
.br
.TP
.B -c 	WiFi QR Create GUI
.br
.TP
.B -t 	WiFi QR Create Terminal
.br
.TP
.B -s 	QR Scan and Auto Connect WiFi
.br
.TP
.B -f	Terminal - QR File Scan and Auto Connect WiFi
.br
.TP
.B -p 	With Gui - QR File Scan and Auto Connect WiFi
.br
.TP
.B -q 	QR Scan and Connect WiFi GUI
.br
.TP
.B -v 	WiFi-QR Version is 0.1.1
.br
.TP
.B -h 	WiFi-QR Help
.br

.SH BUGS
If there are any, please notify the author at the address below.
.SH AUTHOR
kokoye2007 <kokoye2007@gmail.com>

.SH SEE ALSO
.BR qrencode (1), nmcli (1), zbarcam (1), zbarimg (1)
.br
